name = "OmopVocabMapper"
uuid = "fc9e345c-e35d-43ed-87a7-513e2d0ff273"
authors = ["Mounika Thakkallapally <mounika_thakkallapally@brown.edu>, AshlinHarris <ashlin_harris@brown.edu>, and contributors"]
version = "0.1.0-dev"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "^1.7"
