name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        julia-version: ['1.7', '1.8', '1.9']  # Specify the Julia versions you want to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Install dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia --project=@. -e 'using Pkg; Pkg.test()'

      - name: Upload test results (if using Coverage.jl)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test/results/*.jl
